/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AllseasonsPromociones {}
}

declare global {


  interface HTMLAllseasonsPromocionesElement extends Components.AllseasonsPromociones, HTMLStencilElement {}
  var HTMLAllseasonsPromocionesElement: {
    prototype: HTMLAllseasonsPromocionesElement;
    new (): HTMLAllseasonsPromocionesElement;
  };
  interface HTMLElementTagNameMap {
    'allseasons-promociones': HTMLAllseasonsPromocionesElement;
  }
}

declare namespace LocalJSX {
  interface AllseasonsPromociones {}

  interface IntrinsicElements {
    'allseasons-promociones': AllseasonsPromociones;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'allseasons-promociones': LocalJSX.AllseasonsPromociones & JSXBase.HTMLAttributes<HTMLAllseasonsPromocionesElement>;
    }
  }
}


